_pipeline: &pipeline
  build_cache:
    folder: build
    populate_script: mkdir build
  configure_script: meson build
  compile_script: ninja -C build
  test_script: ninja -C build test

debian_gcc_task:
  <<: *pipeline
  container:
    image: snaipe/ci-meson:debian-10

alpine_x86_64_task:
  <<: *pipeline
  container:
    image: snaipe/ci-meson:alpine

alpine_i386_task:
  <<: *pipeline
  container:
    image: snaipe/ci-meson:alpine-x86

alpine_arm_task:
  <<: *pipeline
  container:
    image: snaipe/ci-meson:alpine-armhf

alpine_aarch64_task:
  <<: *pipeline
  container:
    image: snaipe/ci-meson:alpine-aarch64
