_pipeline: &pipeline
  info_script: |
    meson --version
    python --version
    ninja --version
  configure_cache:
    folder: build
    populate_script: meson build
  compile_script: ninja -C build
  test_script: ninja -C build test

debian_gcc_task:
  container:
    image: snaipe/ci-meson:debian-10
  <<: *pipeline

alpine_x86_64_task:
  container:
    image: snaipe/ci-meson:alpine
  <<: *pipeline

alpine_i386_task:
  container:
    image: snaipe/ci-meson:alpine-x86
  <<: *pipeline

alpine_arm_task:
  container:
    image: snaipe/ci-meson:alpine-armhf
  env:
    CIRRUS_SHELL: /sbin/qemu-sh
  <<: *pipeline

alpine_aarch64_task:
  container:
    image: snaipe/ci-meson:alpine-aarch64
  env:
    CIRRUS_SHELL: /sbin/qemu-sh
  <<: *pipeline

macos_task:
  osx_instance:
    image: mojave-xcode-10.2
  setup_script: brew install meson
  <<: *pipeline

freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-0
  setup_script: pkg install -y meson
  <<: *pipeline

windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\\Python;C:\\Python\\Scripts;%PATH%
  meson-setup_cache:
    folder: C:\\Python
    populate_script: |
      choco install -y --no-progress python3 --params "/InstallDir:C:\Python"
      pip install meson
  ninja-setup_cache:
    folder: C:\\Ninja
    populate_script: |
      choco install -y --no-progress ninja --params "/InstallDir:C:\Ninja"
      dir C:\Ninja
  msbuild-setup_script: choco install -y --no-progress microsoft-build-tools
  <<: *pipeline

