_pipeline: &pipeline
  build_cache:
    folder: build
    populate_script: mkdir build
  configure_script: meson build
  compile_script: ninja -C build
  test_script: ninja -C build test

debian_gcc_task:
  container:
    image: snaipe/ci-meson:debian-10
  <<: *pipeline

alpine_x86_64_task:
  container:
    image: snaipe/ci-meson:alpine
  <<: *pipeline

alpine_i386_task:
  container:
    image: snaipe/ci-meson:alpine-x86
  <<: *pipeline

alpine_arm_task:
  container:
    image: snaipe/ci-meson:alpine-armhf
  env:
    CIRRUS_SHELL: /sbin/qemu-sh
  <<: *pipeline

alpine_aarch64_task:
  container:
    image: snaipe/ci-meson:alpine-aarch64
  env:
    CIRRUS_SHELL: /sbin/qemu-sh
  <<: *pipeline
